title: Let's Do The Time Walk Again

description: Website Description (goes in footer).

author:
  name: Site owner name
  email: site_owner@some_domain.com

github:
  owner_name: kent-map
  repository_name: time-walk
  source:
    branch: main

nav_pages:
  - _pages/index.md
  - _articles/index.md
  # - _podcasts/index.md
  - _pages/about/index.md
  # - _pages/contact.md
  # - _admin/index.md
  # - _examples/index.md

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  podcasts:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:collection/:path/
  admin:
    output: true
    permalink: /:collection/:path/
  examples:
    output: true
    permalink: /:collection/:path/

show_excerpts: true
show_rss_feed: false
max-width: 1000px

footer:
  show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
